[project]
name = "flood-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tari", email = "tarinamikpoh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "joblib>=1.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
flood-dataset = "flood_dataset:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
